#! /bin/sh

source ~/.colors

# xrandr --output DVI-D-1 --off
# xrandr --output DVI-I-1 --mode 1920x1200

# Repeat for monitors
# for M in $(bspc quer -M); do
#     bspc config -m $M border_width 0
# done

# Repeat for desktops
# for d in $(bspc query -D); do
#     bspc config -d $d border_width 0
#     bspc config -d $d window_gap 12
# done

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
	    bspc config -m $M $1 $2
	done
}



PADDING=0
desktop_config top_padding         $PADDING + 70
desktop_config right_padding       $PADDING
desktop_config bottom_padding      $PADDING
desktop_config left_padding        $PADDING
desktop_config window_gap       24

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true

desktop_config border_width     1
bspc config normal_border_color #151A21
bspc config active_border_color #151A21
bspc config focused_border_color $COLOR3

bspc config normal_frame_opacity 0.0
bspc config active_frame_opacity 50.0

# Setting up the desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# Custom rules
bspc rule -a lemonbar state=floating

# Kill panel and start
if [ $(pgrep 'panel') ]; then
    pgrep 'panel' | xargs kill -s 9
fi

# conky &
panel &
