#!/bin/bash

source ~/.colors

pkill conky
pkill bar
pkill network
pkill nm-applet
pkill trayer

if [ -z $1 ]
then
  wp change
else
  wp change $1
fi

conky &
panel &
bottombar &
bspc config focused_border_color $COLOR3
