#!/bin/bash


clock() {
  date +%a\ %I:%M\ %p
}

batt() {
  level=$(cat /sys/class/power_supply/BAT0/capacity)
  status=$(cat /sys/class/power_supply/BAT0/status)
  if [ "$level" -lt 20 -a "$status" = "Discharging" ]
  then
    echo "%{F#FFFF3030} $COLOR_OTHER$level"
  elif [ "$status" = "Discharging" ]
  then
    echo "${COLOR_FOREGROUND} $COLOR_OTHER$level" 
  else
    echo "%{F#FF00FF3F} $COLOR_OTHER$level"
  fi
}

vol() {
  level=`(pactl list sinks | grep "Volume: front-left: ")| awk '{print $5}'`
  mute=`amixer get Master | tail -1 | awk '{print $6}' | tr -d '[]'`
  if [ "$mute" == "on" ]
  then
    echo " $COLOR_OTHER$level";
  else
    echo " $COLOR_OTHER$level";
  fi
}

bright() {
  printf "%.0f" `xbacklight -get`
}

info() {
  echo "%{A:urxvt -title 'screenfetch' -e bash -c 'bspc node -t floating;screenfetch -t;read':}Ashwin Sekar%{A}"
}

wifi() {
  waw=`nmcli dev | grep connected | awk '{print $4}'`
  if [ "$waw" == "" ]
  then 
    waw="--"
  fi
  if [[ !first && $waw != $old ]]
  then
    namesize=`inkscape --without-gui --query-id=id1 -W <(echo '<svg><text id="id1" style="font-size:'16'px;font-family:'Inconsolata';">'$waw'</text></svg>') 2>/dev/null`
    namesize=`echo "scale=0; 1.662837 * $namesize + 548.8971" | bc`
    killall trayer
    trayer --widthtype request --heighttype pixel --height $ICON_SIZE \
       --transparent true --alpha 0 --tint $COLOR_BACKGROUND \
       --edge top --distance $TOP_PAD --margin $namesize --align right \
       --SetDockType true --SetPartialStrut false 2>&1 > tray.log &
  fi
  old=$waw
  # 
  buf="$buf$COLOR_FOREGROUND $COLOR_OTHER $waw"
}

# Get our colors
source ~/.colors

COLOR_FOREGROUND="%{F#FF${COLOR3:1}}"
COLOR_OTHER="%{F#FF${COLOR5:1}}"

COLOR_BACKGROUND=0xff151A21
height=`xrandr | grep '*' | cut -d " " -f 4 | cut -d "x" -f 2 | head -n 1`
ICON_SIZE=$(($height / 50))
SLOT_SIZE=$(($height / 37))
TOP_PAD=$((9 + ($SLOT_SIZE - $ICON_SIZE) / 2))
first=true
old=""

while :; do
  buf="$COLOR_FOREGROUND   $(info)"
  buf="$buf%{r}"
  # We have to call the function here cuz we need to update global vars
  wifi

  if [ -d "/sys/class/power_supply/BAT0" ]
  then
    buf="$buf $COLOR_FOREGROUND$(batt)"
  fi

  buf="$buf $COLOR_FOREGROUND$(vol)"

  if [ "`xbacklight 2>&1`" != "No outputs have backlight property" ]
  then
    buf="$buf $COLOR_FOREGROUND$COLOR_OTHER $(bright)"
  fi

  buf="$buf $COLOR_FOREGROUND$COLOR_OTHER $(clock)"
  buf="$buf $COLOR_FOREGROUND%{A:urxvt -e shutdown now:}%{A} $COLOR_FOREGROUND "

  echo $buf
  first=false
done
