#!/bin/bash
source ~/.colors
height=`xrandr | grep '*' | cut -d " " -f 4 | cut -d "x" -f 2 | head -n 1`
width=`xrandr | grep '*' | cut -d " " -f 4 | cut -d "x" -f 1 | head -n 1`

dmenu_run -i -h $height -w $width -q -l 1 -o .9 -p "                                                                                                 execute" -nb "#000000" -nf "#bbbbbb" -sb "#000000" -sf $COLOR3
