#!/bin/bash
# Sample network downspeed, write to temp file
DELAY=2
OUTF1=/tmp/downspeed
OUTF2=/tmp/upspeed
INTERFACE=`ip link | grep BROADCAST,MULTICAST,UP | cut -d ":" -f 2 | tr -d " "`

sample()
{
    rx1=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)
    tx1=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)
    
    sleep $DELAY
    
    rx2=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)
    rxdiff=$[ $rx2 - $rx1 ]
    rxtrue=$[ $rxdiff / 1024 / $DELAY ]

    tx2=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)
    txdiff=$[ $tx2 - $tx1]
    txtrue=$[ $txdiff / 1024 / $DELAY ]
    
    printf "%d" "$rxtrue" > $OUTF1
    printf "%d" "$txtrue" > $OUTF2
}


while true;
do
  $(sample)
done
