#! /bin/sh

if [ $(pgrep -cx float_bar) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

height=`xrandr | grep '*' | cut -d " " -f 4 | cut -d "x" -f 2 | head -n 1`
PANEL_HEIGHT=$(($height / 37))
PANEL_FONT_FAMILY="xft:lemon:pixelsize=18:antialias=true"
#PANEL_FONT_FAMILY="Inconsolata:size=12"
PANEL_ICONS="FontAwesome:size=11"

bspc config top_padding $PANEL_HEIGHT

#bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &


#. panel_colors
source ~/.colors

# Bar requires an alpha channel so I added a fake one
COLOR_FOREGROUND=#FF${COLOR3:1}
COLOR_BACKGROUND=#FF151A21
width=`xrandr | grep '*' | cut -d " " -f 4 | cut -d "x" -f 1 | head -n 1`
width=$(($width - 20))

nmgui 2>&1 > nmgui.log
float_bar | lemonbar -g ${width}x$PANEL_HEIGHT+10+10 -f "$PANEL_FONT_FAMILY" -f "$PANEL_ICONS" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | bash &

wait
